# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

. /usr/local/etc/profile.d/z.sh

# Enable autosuggestions automatically
# zle -N zle-line-init autosuggest_start

# Customize to your needs...

alias stree='/Applications/SourceTree.app/Contents/Resources/stree'

alias workspace="cd ~/workspace"
alias airbnb="cd ~/workspace/airbnb"

#alias wip='git commit -a -m WIP'
#alias squish='git status && git commit -a --amend -C HEAD'

# bind key

bindkey '^[[1;9D' backward-word # iterm
bindkey '^[^[[D' backward-word # tmux os x

bindkey '^[[1;9C' forward-word # iterm
bindkey '^[^[[C' forward-word # tmux os x

if [[ -f "brew" ]]; then
    . `brew --prefix`/etc/profile.d/z.sh
fi

source ~/.aliases

# JAVA

if [[ -f "/usr/libexec/java_home" ]]; then
    export JAVA_HOME=$(/usr/libexec/java_home)
fi
export PATH=$JAVA_HOME/bin:$PATH

# ANDROID

export ANDROID_SDK=$HOME/Library/Android/sdk
export ANDROID_HOME=$ANDROID_SDK
export ANDROID_NDK=$HOME/Library/Android/ndk
export PATH=$PATH:$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools

# Python
export PATH="$HOME/Library/Python/2.7/bin:$PATH"

export PATH="$HOME/.bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# rbenv

eval "$(rbenv init -)"

# AIRLAB-DO-NOT-MODIFY section:ShellWrapper {{{
# Airlab will only make edits inside these delimiters.

# Source Airlab's shell integration, if it exists.
if [ -e ~/.airlab/shellhelper.sh ]; then
  source ~/.airlab/shellhelper.sh
fi
# AIRLAB-DO-NOT-MODIFY section:ShellWrapper }}}

export ONETOUCH_LIB="$HOME/workspace/airbnb/onetouch-lib"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export GOPATH=$HOME/go
export PATH="${PATH}:${GOPATH}/bin"

export I_AM_AN_AIRLAB_DEVELOPER=1
