#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Automatically list directory contents on `cd`.
auto-ls () {
	emulate -L zsh;
	# explicit sexy ls'ing as aliases arent honored in here.
	hash gls >/dev/null 2>&1 && CLICOLOR_FORCE=1 gls -aFh --color --group-directories-first || ls
}
chpwd_functions=( auto-ls $chpwd_functions )


# Enable autosuggestions automatically
#zle -N zle-line-init autosuggest_start

# Customize to your needs...

alias stree='/Applications/SourceTree.app/Contents/Resources/stree'

alias universe="cd ~/Development/exponent/universe"

# Kubectl
kn () {
  export KUBECTL_NAMESPACE=$1
}

alias wip='git commit -a -m WIP'
alias squish='git status && git commit -a --amend -C HEAD'

# bind key

bindkey '^[[1;9D' backward-word # iterm
bindkey '^[^[[D' backward-word # tmux os x

bindkey '^[[1;9C' forward-word # iterm
bindkey '^[^[[C' forward-word # tmux os x

. `brew --prefix`/etc/profile.d/z.sh

source ~/.aliases

# ANDROID

export ANDROID_SDK=$HOME/Library/Android/sdk
export ANDROID_HOME=$ANDROID_SDK
export ANDROID_NDK=$HOME/Library/Android/ndk
export PATH=$PATH:$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools

# Arcanist

export PATH=$PATH:$HOME/.arcanist/arcanist/bin

# Direnv
eval "$(direnv hook zsh)"

# OPAM
#eval `opam config env`

# VAULT TOKEN
export VAULT_AUTH_GITHUB_TOKEN=f8b3fb3ebff7410cd18623fea86d0725043dfc04

# NVM
export EDITOR="vim"

export NVM_DIR="/Users/adam/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

. ~/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

export PATH="$HOME/.yarn/bin:$PATH"
