# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
 
# Enable autosuggestions automatically
# zle -N zle-line-init autosuggest_start

# Customize to your needs...

alias stree='/Applications/SourceTree.app/Contents/Resources/stree'

alias universe="cd ~/Development/exponent/universe"

# Kubectl
kn () {
  export KUBECTL_NAMESPACE=$1
}

#alias wip='git commit -a -m WIP'
#alias squish='git status && git commit -a --amend -C HEAD'

# bind key

bindkey '^[[1;9D' backward-word # iterm
bindkey '^[^[[D' backward-word # tmux os x

bindkey '^[[1;9C' forward-word # iterm
bindkey '^[^[[C' forward-word # tmux os x

. `brew --prefix`/etc/profile.d/z.sh

source ~/.aliases

# ANDROID

export ANDROID_SDK=$HOME/Library/Android/sdk
export ANDROID_HOME=$ANDROID_SDK
export ANDROID_NDK=$HOME/Library/Android/ndk
export PATH=$PATH:$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools

# Arcanist

export PATH=$PATH:$HOME/.arcanist/arcanist/bin

# Direnv
eval "$(direnv hook zsh)"

# Kubectl
kubectl="/Users/adam/Development/exponent/universe/server/infra/tools/.google-cloud-sdk/bin/kubectl"
# source <(${kubectl} completion zsh)
alias k='kubectl "--context=${KUBECTL_CONTEXT:-$(kubectl config current-context)}" ${KUBECTL_NAMESPACE/[[:alnum:]-]*/--namespace="${KUBECTL_NAMESPACE}"}'

# VAULT TOKEN
export VAULT_AUTH_GITHUB_TOKEN=f8b3fb3ebff7410cd18623fea86d0725043dfc04

# NVM
export EDITOR="vim"

export NVM_DIR="/Users/adam/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

export PATH="$HOME/.bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Rust
source $HOME/.cargo/env
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND="rg --files --follow 2> /dev/null"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

